core:
  loader: flash
  beamtime_id: 11013410
  year: 2023
  beamline: pg2
  instrument: hextof
  paths:
    data_raw_dir: "."
    data_parquet_dir: "./parquet"

dataframe:
  ubid_offset: 5
  daq: fl1user3
  channels:

    timeStamp:
      format: per_train
      group_name: "/uncategorised/FLASH.DIAG/TIMINGINFO/TIME1.BUNCH_FIRST_INDEX.1/"

    pulseId:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 2
    dldPosX:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 1
    dldPosY:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 0
    dldTime:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 3
    dldAux:
      format: per_pulse
      group_name : "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 4
      dldAuxChannels:
        sampleBias: 0
        tofVoltage: 1
        extractorVoltage: 2
        extractorCurrent: 3
        cryoTemperature: 4
        sampleTemperature: 5
        crystalVoltage: 6
        dldTimeBinSize: 15


    # ADC containing the pulser sign (1: value approx. 35000, 0: 33000)
    pulserSignAdc:
      format: per_pulse
      group_name: "/FL1/Experiment/PG/SIS8300 100MHz ADC/CH6/TD/"
      #slice: 0

    monochromatorPhotonEnergy:
      format: per_train
      group_name: "/FL1/Beamlines/PG/Monochromator/monochromator photon energy/"


    # The GMDs can not be read yet...
    gmdBda:
      format: per_train
      group_name: "/FL1/Photon Diagnostic/GMD/Average energy/energy BDA/"
    #  slice: ":"

    #gmdTunnel:
    #  format: per_pulse
    #  group_name: "/FL1/Photon Diagnostic/GMD/Pulse resolved energy/energy tunnel/"
    #  slice: ":"

    # Here we use the DBC2 BAM as the "normal" one is broken.
    bam:
        format: per_pulse
        group_name: "/uncategorised/FLASH.SDIAG/BAM.DAQ/FL0.DBC2.ARRIVAL_TIME.ABSOLUTE.SA1.COMP/"

    delayStage:
      format: per_train
      group_name: "/zraw/FLASH.SYNC/LASER.LOCK.EXP/F1.PG.OSC/FMC0.MD22.1.ENCODER_POSITION.RD/dGroup/"


  tof_column: dldTime
  x_column: dldPosX
  y_column: dldPosY
  bias_column: sampleBias
  tof_binning: 3

  stream_name_prefixes:
    pbd: "GMD_DATA_gmd_data"
    pbd2: "FL2PhotDiag_pbd2_gmd_data"
    fl1user1: "FLASH1_USER1_stream_2"
    fl1user2: "FLASH1_USER2_stream_2"
    fl1user3: "FLASH1_USER3_stream_2"
    fl2user1: "FLASH2_USER1_stream_2"
    fl2user2: "FLASH2_USER2_stream_2"
  beamtime_dir:
    pg2: "/asap3/flash/gpfs/pg2/"
    hextof: "/asap3/fs-flash-o/gpfs/hextof/"
    wespe: "/asap3/fs-flash-o/gpfs/wespe/"

nexus:
  reader: "mpes"
  definition: "NXmpes"
  input_files: ["/home/kutnyakd/__beamtimes/Spin_2023/NXmpes_config_HEXTOF_light.json"]
