core:
  loader: flash
  beamtime_id: 11013410
  year: 2023
  beamline: pg2
  instrument: hextof
  paths:
    data_raw_dir: "/path/to/data"
    # change this to a local directory where you want to store the parquet files
    data_parquet_dir: "/path/to/parquet"

binning:
  num_cores: 10

dataframe:
  ubid_offset: 5
  daq: fl1user3
  forward_fill_iterations: 2
  split_sector_id_from_dld_time: True
  sector_id_reserved_bits: 3
  x_column: dldPosX
  corrected_x_column: "X"
  kx_column: "kx"
  y_column: dldPosY
  corrected_y_column: "Y"
  ky_column: "ky"
  tof_column: dldTimeSteps
  tof_ns_column: dldTime
  corrected_tof_column: "tm"
  bias_column: "sampleBias"
  tof_binwidth: 2.0576131995767355E-11 # in seconds
  tof_binning: 3
  sector_id_column: dldSectorID
  sector_delays: [0., 0., 0., 0., 0., 0., 0., 0.]
  jitter_cols: ["dldPosX", "dldPosY", "dldTimeSteps"]

  units:
    dldPosX: 'step'
    dldPosY: 'step'
    dldTimeSteps: 'step'
    tof_voltage: 'V'
    extractorVoltage: 'V'
    extractorCurrent: 'A'
    cryoTemperature: 'K'
    sampleTemperature: 'K'
    dldTime: 'ns'
    # delay: 'ps'
    timeStamp: 's'
    # energy: 'eV'
    # E: 'eV'
    kx: '1/A'
    ky: '1/A'

  channels:
    timeStamp:
      format: per_train
      group_name: "/uncategorised/FLASH.DIAG/TIMINGINFO/TIME1.BUNCH_FIRST_INDEX.1/"
    pulseId:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 2
    dldPosX:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 1
    dldPosY:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 0
    dldTimeSteps:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 3
    dldAux:
      format: per_pulse
      group_name : "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 4
      dldAuxChannels:
        sampleBias: 0
        tofVoltage: 1
        extractorVoltage: 2
        extractorCurrent: 3
        cryoTemperature: 4
        sampleTemperature: 5
        crystalVoltage: 6
        dldTimeBinSize: 15
    pulserSignAdc: # ADC containing the pulser sign (1: value approx. 35000, 0: 33000)
      format: per_pulse
      group_name: "/FL1/Experiment/PG/SIS8300 100MHz ADC/CH6/TD/"
      #slice: 0
    monochromatorPhotonEnergy:
      format: per_train
      group_name: "/FL1/Beamlines/PG/Monochromator/monochromator photon energy/"
    gmdBda: # The GMDs can not be read yet...
      format: per_train
      group_name: "/FL1/Photon Diagnostic/GMD/Average energy/energy BDA/"
    #  slice: ":"
    #gmdTunnel: # The GMDs can not be read yet...
    #  format: per_pulse
    #  group_name: "/FL1/Photon Diagnostic/GMD/Pulse resolved energy/energy tunnel/"
    #  slice: ":"
    bam: # Here we use the DBC2 BAM as the "normal" one is broken.
        format: per_pulse
        group_name: "/uncategorised/FLASH.SDIAG/BAM.DAQ/FL0.DBC2.ARRIVAL_TIME.ABSOLUTE.SA1.COMP/"
    delayStage:
      format: per_train
      group_name: "/zraw/FLASH.SYNC/LASER.LOCK.EXP/F1.PG.OSC/FMC0.MD22.1.ENCODER_POSITION.RD/dGroup/"

  stream_name_prefixes:
    pbd: "GMD_DATA_gmd_data"
    pbd2: "FL2PhotDiag_pbd2_gmd_data"
    fl1user1: "FLASH1_USER1_stream_2"
    fl1user2: "FLASH1_USER2_stream_2"
    fl1user3: "FLASH1_USER3_stream_2"
    fl2user1: "FLASH2_USER1_stream_2"
    fl2user2: "FLASH2_USER2_stream_2"

  beamtime_dir:
    pg2: "/asap3/flash/gpfs/pg2/"
    hextof: "/asap3/fs-flash-o/gpfs/hextof/"
    wespe: "/asap3/fs-flash-o/gpfs/wespe/"

energy:
  calibration:
    d: 2.7342492951998603
    t0: 3.6049383256584405e-08
    E0: -51.289659014865784 # flip sign if switching between kinetic and binding energy
    energy_scale: kinetic
    refid: 3
  offset:
    constant: 2.0
    sampleBias:
      sign: 1
      preserve_mean: True
    monochromatorPhotonEnergy:
      sign: -1
      preserve_mean: True
    tofVoltage:
      sign: -1
      preserve_mean: True
