core:
  loader: sxp
  beamtime_id: p005639
  year: 202302
  beamline: sxp
  instrument: sxp
  paths:
    data_raw_dir: "/path/to/data"
    # change this to a local directory where you want to store the parquet files
    data_parquet_dir: "/path/to/parquet"

binning:
  num_cores: 10

dataframe:
  ubid_offset: 0
  daq: DA03
  forward_fill_iterations: 2
  num_trains: 1
  x_column: dldPosX
  corrected_x_column: "X"
  kx_column: "kx"
  y_column: dldPosY
  corrected_y_column: "Y"
  ky_column: "ky"
  tof_column: dldTimeSteps
  tof_ns_column: dldTime
  corrected_tof_column: "tm"
  bias_column: "sampleBias"
  tof_binwidth: 6.875E-12 # in seconds
  tof_binning: 0
  jitter_cols: ["dldPosX", "dldPosY", "dldTimeSteps"]

  units:
    dldPosX: 'step'
    dldPosY: 'step'
    dldTimeSteps: 'step'
    tof_voltage: 'V'
    extractorVoltage: 'V'
    extractorCurrent: 'A'
    cryoTemperature: 'K'
    sampleTemperature: 'K'
    dldTime: 'ns'
    delay: 'ps'
    delayStage: 'ps'
    timeStamp: 's'
    energy: 'eV'
    # E: 'eV'
    kx: '1/A'
    ky: '1/A'

  channels:
    timeStamp:
      daq: "DA03"
      format: per_train
      dataset_key: "/INDEX/timestamp"
      index_key: "/INDEX/trainId"
      scale: 1000000000
    pulseId:
      daq: "DA03"
      format: per_electron
      dataset_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/starterCounter"
      index_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/trainId"
      max_hits: 10000
    trainId:
      daq: "DA03"
      format: per_electron
      dataset_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/masterCounter"
      index_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/trainId"
      max_hits: 10000
    dldPosX:
      daq: "DA03"
      format: per_electron
      dataset_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/x"
      index_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/trainId"
      max_hits: 10000
    dldPosY:
      daq: "DA03"
      format: per_electron
      dataset_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/y"
      index_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/trainId"
      max_hits: 10000
    dldTimeSteps:
      daq: "DA03"
      format: per_electron
      dataset_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/t"
      index_key: "/INSTRUMENT/SXP_TR_XPES/DET/MCP_CPP_TEST:daqOutput/daqOutput/trainId"
      max_hits: 10000
#    delayStage:
#      format: per_train
#      dataset_key: "/CONTROL/SCS_ILH_LAS/MDL/OPTICALDELAY_PP800/actualPosition/value"
#      index_key: "/INDEX/trainId"
    test:
      daq: DA02
      format: per_pulse
      dataset_key: "/INSTRUMENT/SA3_XTD10_XGM/XGM/DOOCS:output/data/intensitySa3TD"
      index_key: "/INSTRUMENT/SA3_XTD10_XGM/XGM/DOOCS:output/data/trainId"

  stream_name_prefixes:
    DA03: "RAW-R"
  stream_name_postfixes:
    DA03: "-DA03-"

  beamtime_dir:
    sxp: "/gpfs/exfel/exp/SXP/"
