version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    versioning-strategy: "lockfile-only"
    groups:
      dependencies:
        patterns:
          - "*"
