name: sed_env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy>=1.22.2
  - matplotlib>=3.5.1
  - pandas>=1.4.0
  - dask>=2022.01.1
  - xarray>=0.21.1
  - tqdm>=4.62.3
  - scipy>=1.8.0
  - pip>=22.0.3
  - pip:
    - h5py>=3.6.0

  # - fastparquet
  # - pyarrow
  # - tifffile
  # - ipywidgets
