# This file contains the default configuration for the flash loader.

core:
  # defines the loader
  loader: flash

  # the beamline where experiment took place
  beamline: pg2

  # The paths to the raw and parquet data directories.
  paths:
    data_raw_dir: "tests/data/loader/flash/"
    data_parquet_dir: "tests/data/loader/flash/parquet"

  # These can be replaced by beamtime_id and year to automatically
  # find the folders on the desy cluster

  # beamtime_id: xxxxxxxx
  # year: 20xx

dataframe:
  # The name of the DAQ system to use. Necessary to resolve the filenames/paths.
  daq: fl1user3
  # The offset correction to the pulseId
  ubid_offset: 5

  # the number of iterations to fill the pulseId forward.
  forward_fill_iterations: 2
  # if true, removes the 3 bits reserved for dldSectorID from the dldTimeSteps column
  split_sector_id_from_dld_time: True

  sector_id_reserved_bits: 3
  # dataframe column containing x coordinates
  x_column: dldPosX
  # dataframe column containing corrected x coordinates
  corrected_x_column: "X"
  # dataframe column containing kx coordinates
  kx_column: "kx"
  # dataframe column containing y coordinates
  y_column: dldPosY
  # dataframe column containing corrected y coordinates
  corrected_y_column: "Y"
  # dataframe column containing kx coordinates
  ky_column: "ky"
  # dataframe column containing time-of-flight data
  tof_column: dldTimeSteps
  # dataframe column containing time-of-flight data in ns
  tof_ns_column: dldTime
  # dataframe column containing corrected time-of-flight data
  corrected_tof_column: "tm"
  # time length of a base time-of-flight bin in seconds
  tof_binwidth: 2.0576131995767355E-11
  # binning parameter for time-of-flight data. 2**tof_binning bins per base bin
  tof_binning: 3  # power of 2, 3 means 8 bins per step
  # dataframe column containing sector ID. obtained from dldTimeSteps column
  sector_id_column: dldSectorID

  sector_delays: [0., 0., 0., 0., 0., 0., 0., 0.]
  # the delay stage column
  delay_column: delayStage
  # the corrected pump-probe time axis
  corrected_delay_column: pumpProbeTime
  jitter_cols: ["dldPosX", "dldPosY", "dldTimeSteps"]

  units:
    dldPosX: 'step'
    dldPosY: 'step'
    dldTimeSteps: 'step'
    tof_voltage: 'V'
    extractorVoltage: 'V'
    extractorCurrent: 'A'
    cryoTemperature: 'K'
    sampleTemperature: 'K'
    dldTime: 'ns'
    # delay: 'ps'
    timeStamp: 's'
    # energy: 'eV'
    # E: 'eV'
    kx: '1/A'
    ky: '1/A'

  # The channels to load.
  # channels have the following structure:
  # channelAlias:
  #   format: per_pulse/per_electron/per_train
  #   group_name: the hdf5 group path
  #   slice: if the group contains multidim data, where to slice

  channels:
    # pulse ID is a necessary channel for using the loader.
    pulseId:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 2

    dldPosX:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 1

    dldPosY:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 0
    # This channel will actually create dldTimeSteps and dldSectorID,
    # if unravel_8s_detector_time_channel is set to True
    dldTimeSteps:
      format: per_electron
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 3

    # The auxillary channel has a special structure where the group further contains
    # a multidim structure so further aliases are defined below
    dldAux:
      format: per_pulse
      group_name: "/uncategorised/FLASH.EXP/HEXTOF.DAQ/DLD1/"
      slice: 4
      dldAuxChannels:
        sampleBias: 0
        tofVoltage: 1
        extractorVoltage: 2
        extractorCurrent: 3
        cryoTemperature: 4
        sampleTemperature: 5
        dldTimeBinSize: 15

  # The prefixes of the stream names for different DAQ systems for parsing filenames
  # (Not to be changed by user)
  stream_name_prefixes:
    pbd: "GMD_DATA_gmd_data"
    pbd2: "FL2PhotDiag_pbd2_gmd_data"
    fl1user1: "FLASH1_USER1_stream_2"
    fl1user2: "FLASH1_USER2_stream_2"
    fl1user3: "FLASH1_USER3_stream_2"
    fl2user1: "FLASH2_USER1_stream_2"
    fl2user2: "FLASH2_USER2_stream_2"

  # The beamtime directories for different DAQ systems.
  # (Not to be changed by user)
  beamtime_dir:
    pg2: "/asap3/flash/gpfs/pg2/"

# metadata collection from scicat
# metadata:
#   scicat_url: <URL>
#   scicat_username: <username>
#   scicat_password: <password>

# The nexus collection routine shall be finalized soon for both instruments
# nexus:
#   reader: "flash"
#   definition: "NXmpes"
#   input_files: ["NXmpes_config_HEXTOF_light.json"]
