name: autogenerate docs from tutorials
on:
  # Triggers the workflow on push but only for the main branch
  push:
    branches: [ auto-doc-generation ]
    paths: ['**.ipynb']

jobs:
  docs-from-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-android: 'true'
          remove-docker-images: 'true'
          
      #  Check out repo and set up Python
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          lfs: true
    
      # Use cached python and dependencies, install poetry
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
      
      - name: Install jupyter
        run: poetry install -E notebook

      - name: Install pandoc
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb
          sudo dpkg -i pandoc-3.1.8-1-amd64.deb

      # Execute and convert notebooks
      - name: execute notebooks
        run: find $GITHUB_WORKSPACE/tutorial -type f -name "*.ipynb" -exec poetry run jupyter-nbconvert --execute --to notebook --inplace {} \;
      
      - name: create docs/tutorial directory
        run: mkdir -p $GITHUB_WORKSPACE/docs/tutorial

      - name: convert notebooks to rst and save to docs
        run: find $GITHUB_WORKSPACE/tutorial -type f -name "*.ipynb" -exec poetry run jupyter-nbconvert --to rst --output-dir $GITHUB_WORKSPACE/docs/tutorial {} \;

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating tutorial rsts for docs'
          add: 'docs/tutorial/'