name: linting

# Triggers the workflow on push for all branches
on:
  push:
    paths-ignore:
      pyproject.toml

env:
  UV_SYSTEM_PYTHON: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up Python
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install package
        run: |
          uv pip install ".[dev]"

      # Linting steps, execute all linters even if one fails
      - name: ruff
        run:
          ruff src/sed tests
      - name: ruff formatting
        if: ${{ always() }}
        run:
          ruff format --check src/sed tests
      - name: mypy
        if: ${{ always() }}
        run:
          mypy src/sed tests
      - name: spellcheck
        if: ${{ always() }}
        uses: streetsidesoftware/cspell-action@v6
        with:
          check_dot_files: false
          incremental_files_only: false
          config: './cspell.json'
