name: linting

# Triggers the workflow on push for all branches
on:
  push:
    paths-ignore:
      pyproject.toml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up Python
      - uses: actions/checkout@v4
        with:
          lfs: true

      # Use cached python and dependencies, install poetry
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.9
          poetry-version: 1.8.3

      # Linting steps, excute all linters even if one fails
      - name: ruff
        run:
          poetry run ruff sed tests
      - name: ruff formating
        if: ${{ always() }}
        run:
          poetry run ruff format --check sed tests
      - name: mypy
        if: ${{ always() }}
        run:
          poetry run mypy sed tests
      - name: spellcheck
        if: ${{ always() }}
        uses: streetsidesoftware/cspell-action@v6
        with:
          check_dot_files: false
          incremental_files_only: false
          config: './cspell.json'
          verbose: true

