# This workflow will install Python dependencies, lint and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# TODO: switch to the cached version
name: linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [pylint, mypy, flake8]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ${{ matrix.linter }}
