
name: Publish to PyPI Test

on:
  push:
    branches:
      - publish-pypi

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up Python
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: 'sed-processor'
      - run: |
          ls -lha


      # Use cached python and dependencies, install poetry
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2

      - name: Change to distribution name in toml file
        run: sed -i 's/name = "sed"/name = "sed-processor"/' pyproject.toml


      - name: Build package
        run: poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build-package
    environment:
        name: test-pypi
        url: https://test.pypi.org/p/sed-processor
    permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
        # retrieving distributions here
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish package distributions to PyPI Test
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST }}
          packages-dir: .
