name: Publish to PyPI Test

on:
  push:
    branches:
      - publish-pypi
    tags:
      - '*'

jobs:
  pre-release:
    if: github.ref == 'refs/heads/publish-pypi'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: 'sed-processor'

      - name: "Setup Python, Poetry and Dependencies"
        uses: zain-sohail/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
          working-directory: sed-processor

      - name: Change to distribution name in toml file
        run: |
          cd sed-processor
          sed -i 's/name = "sed"/name = "sed-processor"/' pyproject.toml

      - name: bump pre-release version
        run: |
          cd sed-processor
          poetry version prerelease
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: sed-processor/dist

  pypi-test-publish:
    runs-on: ubuntu-latest
    needs: pre-release
    environment:
        name: test-pypi
        url: https://test.pypi.org/p/sed-processor
    permissions:
        id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish package distributions to PyPI Test
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST }}
          packages-dir: .

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: 'sed-processor'

      - name: "Setup Python, Poetry and Dependencies"
        uses: zain-sohail/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
          working-directory: sed-processor

      - name: Change to distribution name in toml file
        run: |
          cd sed-processor
          sed -i 's/name = "sed"/name = "sed-processor"/' pyproject.toml

      - name: Update version in pyproject.toml and build
        run: |
          cd sed-processor
          VERSION=$(echo ${GITHUB_REF#refs/tags/v} | sed 's/-.*//')
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: sed-processor/dist

  pypi-publish:
    needs: release
    runs-on: ubuntu-latest
    environment:
        name: test-pypi
        url: https://test.pypi.org/p/sed-processor
    permissions:
        id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish package distributions to PyPI Test
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST }}
          packages-dir: .
