# This workflow will install Python dependencies, lint and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        git lfs pull
        python -m pip install --upgrade pip
        pip install pycodestyle pylint mypy pytest types-PyYAML types-requests coverage coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install package
      run: |
        python -m pip install .
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E203,E501,W503 sed tests
    - name: pylint
      if: ${{ always() }}
      run: |
        python -m pylint --good-names=i,j,k,ex,x,y,t,k,v,ax,df,ec,mc,dc,ct --disable=fixme,too-many-branches,too-many-locals,too-many-statements,too-many-arguments,too-many-lines,too-many-public-methods,too-many-instance-attributes,too-few-public-methods sed tests
    - name: mypy
      if: ${{ always() }}
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional sed tests
    - name: Test with pytest
      if: ${{ always() }}
      run: |
        coverage run -m pytest -sv --show-capture=no tests
    - name: Submit to coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
