# This workflow will install Python dependencies, run tests for a single versions of Python and commit test results to coveralls
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        git lfs pull
        python -m pip install --upgrade pip
        python -m pip install pytest coverage coveralls
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        coverage run -m pytest -sv --show-capture=no tests
    - name: Submit to coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github
