name: Publish to PyPI

on:
  push:
    branches:
      - publish-pypi
    tags:
      - '*'

jobs:
  prerelease:
    # change to main later
    if: github.ref == 'refs/heads/publish-pypi'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: 'sed-processor'

      - name: "Setup Python, Poetry and Dependencies"
        uses: zain-sohail/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
          working-directory: sed-processor

      - name: Change to distribution name in toml file
        run: |
          cd sed-processor
          sed -i 's/name = "sed"/name = "sed-processor"/' pyproject.toml

      - name: bump pre-release version
        id: version
        working-directory: sed-processor
        run: |
          VERSION=$(poetry version -s prerelease)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: sed-processor/dist

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          path: 'sed-processor'

      - name: "Setup Python, Poetry and Dependencies"
        uses: zain-sohail/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
          working-directory: sed-processor

      - name: Change to distribution name in toml file
        run: |
          cd sed-processor
          sed -i 's/name = "sed"/name = "sed-processor"/' pyproject.toml

      - name: Bump release version and build
        id: version
        working-directory: sed-processor
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/tags/v} | sed 's/-.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          poetry version $VERSION
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: sed-processor/dist

  publish:
    needs: [prerelease, release]
    if: needs.prerelease.result == 'success' || needs.release.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.prerelease.outputs.version || needs.release.outputs.version }}
    environment:
        name: pypi
        url: https://pypi.org/p/sed-processor
    permissions:
        id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish package distributions to PyPI Test
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: .

  bump-version:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'bump version to ${{ needs.publish.outputs.version }}'
        add: pyproject.toml
        cwd: sed-processor
        new_branch: publish-pypi
        # By default, a workflow run that is triggered by a push event will
        # not trigger another push event when it pushes changes to the repository.
        # So no problem here.
