name: pytest

# Triggers the workflow on push for all branches
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up Python
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Use cached python and dependencies, install poetry
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2
      
      - name: Install dependencies
        run:
          python -m pip install pytest coverage coveralls
      
      # Run pytest with coverage report and upload results to coveralls
      - name: Run tests on python 3.8
        run: |
          coverage run -m pytest --full-trace --show-capture=no -sv tests
      
      - name: Submit to coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github
