name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  pytest:
    # Using matrix strategy
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      #-------------------------------------#
      #  Check out repo and set up Python   #
      #-------------------------------------#
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # - name: "Setup Python and Dependencies"
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{matrix.python-version}}
      #     check-latest: true
      #     cache: 'poetry' # caching poetry dependencies

      #------------------------#
      #  Run pytest
      #------------------------#
      - name: Run tests
        run: |
          poetry run pytest --cov=sed -n auto tests/

      # Coveralls missing
      - name: Coveralls
        uses: coverallsapp/github-action@v2
