name: unit tests [Python 3.8|3.9|3.10]

on:
  push:
    paths-ignore:
      pyproject.toml

jobs:
  pytest:
    # Using matrix strategy
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up Python
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: ${{matrix.python-version}}
          poetry-version: 1.2.2

      # Use cached python and dependencies, install poetry
      - name: Run tests on python ${{matrix.python-version}}
        run: |
          poetry run pytest --full-trace --show-capture=no -sv -n auto tests/
